apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    app: employees
spec:
  containers:
  - name: web-app
    image: 237049620366.dkr.ecr.us-east-1.amazonaws.com/my-webapp-repo:latest
    ports:
    - containerPort: 8080

